In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
input_file_name = './data/Imbalance Ratio.csv'
imbalance = pd.read_csv(input_file_name, sep = ",")
# drop the first unamed column 
imbalance = imbalance.drop(imbalance.columns[0], axis = 1)
imbalance = imbalance.rename(columns={"station number": "Station"})
imbalance[:10]

   Station  bikes out  bikes in  diff  diff_abs  imbalance ratio
0    31000        115       152    37        37         0.321739
1    31001        142       118   -24        24         0.203390
2    31002        259       297    38        38         0.146718
3    31003        198       234    36        36         0.181818
4    31004        158       154    -4         4         0.025974
5    31005        327       317   -10        10         0.031546
6    31006        146       181    35        35         0.239726
7    31007        455       382   -73        73         0.191099
8    31008        228       234     6         6         0.026316
9    31009        208       186   -22        22         0.118280

In [5]:
imbalance['ratio'] = 10*imbalance[['diff']].div(imbalance[['bikes out', 'bikes in']].min(axis=1), axis=0)
imbalance['class'] = np.where(imbalance['diff']>=0, 1, 0)
imbalance

,Station,bikes out,bikes in,diff,diff_abs,imbalance ratio,ratio,class
0,31000,115,152,37,37,0.321739,3.217391,1
1,31001,142,118,-24,24,0.203390,-2.033898,0
2,31002,259,297,38,38,0.146718,1.467181,1
3,31003,198,234,36,36,0.181818,1.818182,1
4,31004,158,154,-4,4,0.025974,-0.259740,0
5,31005,327,317,-10,10,0.031546,-0.315457,0
6,31006,146,181,35,35,0.239726,2.397260,1
7,31007,455,382,-73,73,0.191099,-1.910995,0
8,31008,228,234,6,6,0.026316,0.263158,1
9,31009,208,186,-22,22,0.118280,-1.182796,0
10,31010,139,138,-1,1,0.007246,-0.072464,0
11,31011,191,260,69,69,0.361257,3.612565,1
12,31012,152,133,-19,19,0.142857,-1.428571,0
13,31013,113,119,6,6,0.053097,0.530973,1
14,31014,550,852,302,302,0.549091,5.490909,1
15,31015,214,445,231,231,1.079439,10.794393,1
16,31016,254,228,-26,26,0.114035,-1.140351,0
17,31017,268,138,-130,130,0.942029,-9.420290,0
18,31018,114,87,-27,27,0.310345,-3.103448,0
19,31019,136,121,-15,15,0.123967,-1.239669,0
20,31020,188,118,-70,70,0.593220,-5.932203,0
21,31021,192,142,-50,50,0.352113,-3.521127,0
22,31022,301,222,-79,79,0.355856,-3.558559,0
23,31023,150,126,-24,24,0.190476,-1.904762,0
24,31024,406,375,-31,31,0.082667,-0.826667,0
25,31025,105,93,-12,12,0.129032,-1.290323,0
26,31026,150,75,-75,75,1.000000,-10.000000,0
27,31027,101,81,-20,20,0.246914,-2.469136,0
28,31028,63,49,-14,14,0.285714,-2.857143,0
29,31029,214,183,-31,31,0.169399,-1.693989,0
...,...,...,...,...,...,...,...,...
454,32067,106,107,1,1,0.009434,0.094340,1
455,32068,76,61,-15,15,0.245902,-2.459016,0
456,32069,10,10,0,0,0.000000,0.000000,1
457,32072,1,3,2,2,2.000000,20.000000,1
458,32073,1,1,0,0,0.000000,0.000000,1
459,32200,6,7,1,1,0.166667,1.666667,1
460,32201,3,3,0,0,0.000000,0.000000,1
461,32203,11,13,2,2,0.181818,1.818182,1
462,32204,47,52,5,5,0.106383,1.063830,1
463,32205,20,21,1,1,0.050000,0.500000,1
464,32206,11,11,0,0,0.000000,0.000000,1
465,32207,7,9,2,2,0.285714,2.857143,1
466,32208,10,11,1,1,0.100000,1.000000,1
467,32209,11,6,-5,5,0.833333,-8.333333,0
468,32210,5,11,6,6,1.200000,12.000000,1
469,32211,1,2,1,1,1.000000,10.000000,1
470,32212,2,2,0,0,0.000000,0.000000,1
471,32213,35,36,1,1,0.028571,0.285714,1
472,32214,55,64,9,9,0.163636,1.636364,1
473,32215,171,131,-40,40,0.305344,-3.053435,0
474,32216,18,27,9,9,0.500000,5.000000,1
475,32217,26,19,-7,7,0.368421,-3.684211,0
476,32218,6,5,-1,1,0.200000,-2.000000,0
477,32219,15,24,9,9,0.600000,6.000000,1
478,32220,31,41,10,10,0.322581,3.225806,1
479,32221,28,18,-10,10,0.555556,-5.555556,0
480,32222,1,1,0,0,0.000000,0.000000,1
481,32223,10,15,5,5,0.500000,5.000000,1
482,32224,5,8,3,3,0.600000,6.000000,1
483,32225,4,2,-2,2,1.000000,-10.000000,0

In [7]:


import json
import pandas as pd
with open('../map-inventory.json', 'r') as f:
    map_station = json.load(f)
map_station = map_station['features']
map_station_data = []
# w/o station name
# for each in map_station:
#     map_station_data.append([int(each['properties']['station']['terminal']),each['geometry']['coordinates'][0],each['geometry']['coordinates'][1]]) 
# map_station_data= pd.DataFrame(map_station_data, columns = ['Station', 'longitude', 'latitude'])

# w/ station name
for each in map_station:
    map_station_data.append([int(each['properties']['station']['terminal']),each['properties']['station']['name'],each['geometry']['coordinates'][0],each['geometry']['coordinates'][1]]) 
map_station_data= pd.DataFrame(map_station_data, columns = ['Station', 'name','longitude', 'latitude'])

# map_station_data

In [8]:
imbalance_map = pd.merge(imbalance, map_station_data, on='Station')
imbalance_map[:20]

,Station,bikes out,bikes in,diff,diff_abs,imbalance ratio,ratio,class,name,longitude,latitude
0,31000,115,152,37,37,0.321739,3.217391,1,Eads St & 15th St S,-77.053230,38.858971
1,31001,142,118,-24,24,0.203390,-2.033898,0,18th St & S Eads St,-77.053320,38.857250
2,31002,259,297,38,38,0.146718,1.467181,1,Crystal Dr & 20th St S,-77.049232,38.856425
3,31003,198,234,36,36,0.181818,1.818182,1,Crystal Dr & 15th St S,-77.049593,38.860170
4,31004,158,154,-4,4,0.025974,-0.259740,0,Aurora Hills Cmty Ctr / 18th St & S Hayes St,-77.059490,38.857866
5,31005,327,317,-10,10,0.031546,-0.315457,0,Pentagon City Metro / 12th St & S Hayes St,-77.059936,38.862303
6,31006,146,181,35,35,0.239726,2.397260,1,Army Navy Dr & S Joyce St,-77.063300,38.863700
7,31007,455,382,-73,73,0.191099,-1.910995,0,Crystal City Metro / 18th St & S Bell St,-77.051132,38.857405
8,31009,208,186,-22,22,0.118280,-1.182796,0,Crystal Dr & 27th St S,-77.051514,38.848466
9,31010,139,138,-1,1,0.007246,-0.072464,0,S Glebe Rd & Potomac Ave,-77.050200,38.842600
10,31011,191,260,69,69,0.361257,3.612565,1,Crystal Dr & 23rd St S,-77.049800,38.853300
11,31012,152,133,-19,19,0.142857,-1.428571,0,Clark St & 26th St S,-77.051520,38.850688
12,31013,113,119,6,6,0.053097,0.530973,1,Eads St & 22nd St S,-77.053412,38.854381
13,31014,550,852,302,302,0.549091,5.490909,1,Lynn St & 19th St North,-77.070993,38.897315
14,31015,214,445,231,231,1.079439,10.794393,1,Rosslyn Metro / Wilson Blvd & Ft Myer Dr,-77.072305,38.894600
15,31016,254,228,-26,26,0.114035,-1.140351,0,Clarendon Blvd & Pierce St,-77.076389,38.893438
16,31017,268,138,-130,130,0.942029,-9.420290,0,Wilson Blvd & N Uhle St,-77.084600,38.891696
17,31018,114,87,-27,27,0.310345,-3.103448,0,Rhodes St & 16th St N,-77.079375,38.892164
18,31019,136,121,-15,15,0.123967,-1.239669,0,Wilson Blvd & N Edgewood St,-77.092500,38.889000
19,31020,188,118,-70,70,0.593220,-5.932203,0,Wilson Blvd & N Franklin Rd,-77.088900,38.890400

In [9]:
output_file_name_map = './data/imbalance ratio map.csv'
imbalance_map.to_csv(output_file_name_map)